// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiyKfnzcZ-mCKzgIe-pei1pW2CArZ6EF0',
    appId: '1:835363681284:web:87a75201859e9d54817151',
    messagingSenderId: '835363681284',
    projectId: 'my-first-firebase-projec-1c246',
    authDomain: 'my-first-firebase-projec-1c246.firebaseapp.com',
    storageBucket: 'my-first-firebase-projec-1c246.firebasestorage.app',
    measurementId: 'G-1RLZJY17HH',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcZvCh0f_070j23Un9A9x51jh_JxAvWhQ',
    appId: '1:835363681284:ios:ba0b5aa123270bb0817151',
    messagingSenderId: '835363681284',
    projectId: 'my-first-firebase-projec-1c246',
    storageBucket: 'my-first-firebase-projec-1c246.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiyKfnzcZ-mCKzgIe-pei1pW2CArZ6EF0',
    appId: '1:835363681284:web:87a75201859e9d54817151',
    messagingSenderId: '835363681284',
    projectId: 'my-first-firebase-projec-1c246',
    authDomain: 'my-first-firebase-projec-1c246.firebaseapp.com',
    storageBucket: 'my-first-firebase-projec-1c246.firebasestorage.app',
    measurementId: 'G-1RLZJY17HH',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcZvCh0f_070j23Un9A9x51jh_JxAvWhQ',
    appId: '1:835363681284:ios:ba0b5aa123270bb0817151',
    messagingSenderId: '835363681284',
    projectId: 'my-first-firebase-projec-1c246',
    storageBucket: 'my-first-firebase-projec-1c246.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfpvfA9RpwQf2EqT3B1-COalpGvW303Zg',
    appId: '1:835363681284:android:8fc2a850509b98dc817151',
    messagingSenderId: '835363681284',
    projectId: 'my-first-firebase-projec-1c246',
    storageBucket: 'my-first-firebase-projec-1c246.firebasestorage.app',
  );

}